name: Publish Sheep Dog Dev MCP Release

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  sheep-dog-dev-mcp:
    uses: farhan5248/sheep-dog-ops/.github/workflows/maven-release.yml@main
    with:
      project: 'sheep-dog-dev-mcp'
      plugin: 'Maven'
    secrets: inherit

  merge-into-develop:
    needs: [sheep-dog-dev-mcp]
    uses: farhan5248/sheep-dog-ops/.github/workflows/merge.yml@main
    with:
      source: 'main'
      target: 'develop'
    secrets: inherit
